# Generated by Django 4.0.3 on 2022-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('pinCode', models.IntegerField()),
                ('total', models.FloatField()),
                ('studentStrength', models.FloatField()),
                ('facultyStudentRatio', models.FloatField()),
                ('facultyExperience', models.FloatField()),
                ('financialResource', models.FloatField()),
                ('onlineEducation', models.FloatField()),
                ('combPublicationMetric', models.FloatField()),
                ('qualOfPublication', models.FloatField()),
                ('iprPatents', models.FloatField()),
                ('footPrint', models.FloatField()),
                ('graduationOutcome', models.FloatField()),
                ('phdOutcome', models.FloatField()),
                ('otherStateStudent', models.FloatField()),
                ('womenPercentage', models.FloatField()),
                ('economicallyChallenged', models.FloatField()),
                ('physicallyChallenged', models.FloatField()),
                ('perception', models.FloatField()),
            ],
        ),
    ]
